# Build settings

port: 4000
markdown:  kramdown
permalink: /:title
plugins:   [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:        "자기소개"
description: "Powered by Jekyll and GitHub Pages"
author:      "유태희"
email:       "taeheeyu@gmail.com"
